replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prd"
  hosts:
    - host: "container.eks.openbankingpx.tk"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: "eks-hello-app-container-cert"
     hosts:
       - "container.eks.openbankingpx.tk"
